name: Deploy to AWS

on:
  push:
    branches:
      - main
    paths:
      - 'app/**'
      - 'terraform/**'
      - '.github/workflows/deploy.yml'
  workflow_dispatch:  # Manual trigger

env:
  AWS_REGION: us-east-2
  PROJECT_NAME: multi-orchestrator-app
  ENVIRONMENT: prod
  TF_VERSION: 1.5.0

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    
    outputs:
      ecr_repo_url: ${{ steps.build.outputs.ecr_repo_url }}
      image_tag: ${{ steps.build.outputs.image_tag }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and Push Docker image
      id: build
      run: |
        ECR_REPO=${{ secrets.ECR_REPOSITORY }}
        IMAGE_TAG=$(git rev-parse --short HEAD)
        
        # Build the image
        docker build -t $ECR_REPO:$IMAGE_TAG ./app
        
        # Push the image
        docker push $ECR_REPO:$IMAGE_TAG
        
        # Set outputs
        echo "ecr_repo_url=$ECR_REPO" >> $GITHUB_OUTPUT
        echo "image_tag=$IMAGE_TAG" >> $GITHUB_OUTPUT

  terraform-plan:
    runs-on: ubuntu-latest
    needs: build-and-push
    permissions:
      id-token: write
      contents: read
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Terraform Init
      run: |
        cd terraform
        terraform init \
          -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}" \
          -backend-config="key=${{ env.PROJECT_NAME }}/terraform.tfstate" \
          -backend-config="region=${{ env.AWS_REGION }}"

    - name: Terraform Plan
      run: |
        cd terraform
        terraform plan \
          -var="aws_region=${{ env.AWS_REGION }}" \
          -var="project_name=${{ env.PROJECT_NAME }}" \
          -var="environment=${{ env.ENVIRONMENT }}" \
          -var="ecr_image_tag=${{ needs.build-and-push.outputs.image_tag }}" \
          -out=tfplan

  terraform-apply:
    runs-on: ubuntu-latest
    needs: terraform-plan
    permissions:
      id-token: write
      contents: read
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Terraform Apply
      run: |
        cd terraform
        terraform apply -auto-approve tfplan

    - name: Deploy to EKS
      run: |
        # Update kubeconfig
        aws eks update-kubeconfig \
          --region ${{ env.AWS_REGION }} \
          --name ${{ env.PROJECT_NAME }}-eks-cluster
        
        # Replace placeholders in Kubernetes manifest
        export ECR_REPOSITORY_URL=${{ needs.build-and-push.outputs.ecr_repo_url }}
        export IMAGE_TAG=${{ needs.build-and-push.outputs.image_tag }}
        
        envsubst < kubernetes/deployment.yaml > kubernetes/deployment-processed.yaml
        
        # Apply Kubernetes manifest
        kubectl apply -f kubernetes/deployment-processed.yaml
        
        # Wait for service to be ready
        kubectl rollout status deployment/web-app --timeout=300s

  test-deployments:
    runs-on: ubuntu-latest
    needs: terraform-apply
    permissions:
      id-token: write
      contents: read
    
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Get ECS Load Balancer DNS
      id: get-ecs-dns
      run: |
        cd terraform
        ECS_URL=$(terraform output -raw ecs_service_url)
        echo "ECS_URL=$ECS_URL" >> $GITHUB_ENV

    - name: Get EKS Load Balancer DNS
      id: get-eks-dns
      run: |
        aws eks update-kubeconfig \
          --region ${{ env.AWS_REGION }} \
          --name ${{ env.PROJECT_NAME }}-eks-cluster
        
        EKS_URL=$(kubectl get service web-service -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
        echo "EKS_URL=$EKS_URL" >> $GITHUB_ENV

    - name: Test ECS Deployment
      run: |
        echo "Testing ECS deployment at $ECS_URL..."
        sleep 30  # Wait for ALB to be ready
        curl -f http://$ECS_URL:8080/ || echo "ECS test failed"
        curl -f http://$ECS_URL:8080/health || echo "ECS health check failed"

    - name: Test EKS Deployment
      run: |
        echo "Testing EKS deployment at $EKS_URL..."
        sleep 30  # Wait for ELB to be ready
        curl -f http://$EKS_URL/ || echo "EKS test failed"
        curl -f http://$EKS_URL/health || echo "EKS health check failed"